services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
        FLIGHT_DATA_PATH: ${CONTAINER_DATA_PATH:-/data/merged_flight_weather_data.csv}
        MODEL_PATH: ${CONTAINER_MODEL_PATH:-/models/flight_delay_model.pkl}
    volumes:
        - ../merged_flight_weather_data.csv:${CONTAINER_DATA_PATH:-/data/merged_flight_weather_data.csv}:ro
        - ./backend/models:${CONTAINER_MODEL_DIR:-/models}
    ports:
      - "8000:8000"

  gradio:
    build:
      context: .
      dockerfile: frontend/Gradio.Dockerfile
    environment:
      API_BASE_URL: http://api:8000
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
    depends_on:
      - api
    ports:
      - "7860:7860"
